### ISSUE TITLE
Group Functionality for Teams

### ISSUE THREAD

**Issue by nikohd12** [coccoinomane/crabada.py#56] opened 2022-04-15 07:53 UTC
Hi @coccoinomane, @yigitest, and the rest of the crew,

I'm curious to know if you think this is a valid or needed feature: **Grouping of Teams**

Basically, our current .env file right now looks like this (trimmed to 8 teams for easy comparison):
```
# =========
# = TEAMS =
# =========
USER_1_TEAM_1="1111"
USER_1_TEAM_1_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_TEAM_1_TASK="mine"
USER_1_TEAM_1_REINFORCEMENT_TO_PICK="3"
USER_1_TEAM_2="1111"
USER_1_TEAM_2_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_TEAM_2_TASK="mine"
USER_1_TEAM_2_REINFORCEMENT_TO_PICK="3"
USER_1_TEAM_3="1111"
USER_1_TEAM_3_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_TEAM_3_TASK="mine"
USER_1_TEAM_3_REINFORCEMENT_TO_PICK="3"
USER_1_TEAM_4="1111"
USER_1_TEAM_4_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_TEAM_4_TASK="mine"
USER_1_TEAM_4_REINFORCEMENT_TO_PICK="3"
USER_1_TEAM_5="1111"
USER_1_TEAM_5_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_TEAM_5_TASK="mine"
USER_1_TEAM_5_REINFORCEMENT_TO_PICK="3"
USER_1_TEAM_6="1111"
USER_1_TEAM_6_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_TEAM_6_TASK="mine"
USER_1_TEAM_6_REINFORCEMENT_TO_PICK="3"
USER_1_TEAM_7="1111"
USER_1_TEAM_7_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_TEAM_7_TASK="mine"
USER_1_TEAM_7_REINFORCEMENT_TO_PICK="3"
USER_1_TEAM_8="1111"
USER_1_TEAM_8_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_TEAM_8_TASK="mine"
```

Now, I think we could group this by doing separate .env files or creating new folders per group. But what if we can make this a little bit cleaner by adding a group functionality.

Some features on top of my head that grouping might introduce:
- Ability to create different strategies for different classes (Machines, Lux, Sunken, Ruineds, etc)
- Cleaner looking .env files, IMO most of us use the same strategy for **Reinforcement to Pick** for example, or Reinforce Strategy, so it would look cleaner by having a group
- A possibility to introduce staggering mines by having a check before deploying other groups (is this possible?)
- Lastly, the ability to group Looters and Miners together without looking messy

The .env file would look something like this:

```
# =========
# = MINERS =
# =========
USER_1_GROUP_1_TEAMS=[1111,2222,3333,4444]
USER_1_GROUP_1_TASK="mine"
USER_1_GROUP_1_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_GROUP_1_REINFORCEMENT_TO_PICK="3"

# =========
# = LOOTERS =
# =========
USER_1_GROUP_2_TEAMS=[5555,6666,7777,8888]
USER_1_GROUP_2_TASK="loot"
USER_1_GROUP_2_REINFORCE_STRATEGY="HighestBpFromInventory, HighestBpHighCost, HighestBp"
USER_1_GROUP_2_REINFORCEMENT_TO_PICK="3"
```

or a staggered mine, where MINERS 2 can check if miners from MINERS 1 have a 30-minute gap for self-reinforce. Else, do not mine.

```
# =========
# = MINERS 1 =
# =========
USER_1_GROUP_1_TEAMS=[1111,2222]
USER_1_GROUP_1_TASK="mine"
USER_1_GROUP_1_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_GROUP_1_REINFORCEMENT_TO_PICK="3"

# =========
# = MINERS 2 =
# =========
USER_1_GROUP_2_TEAMS=[3333,4444]
USER_1_GROUP_2_TASK="mine"
USER_1_GROUP_2_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_GROUP_2_REINFORCEMENT_TO_PICK="3"
```

**Comment by coccoinomane** [comment] 2022-04-15 16:44
The group functionality seems like a nice feature @nikohd12 ... I never thought about it because I only have one team 😂

The most challenging point to implement would be:

>A possibility to introduce staggering mines by having a check before deploying other groups (is this possible?)

Maybe we can go ahead with grouping and leave this for later.

**Comment by nikohd12** [comment] 2022-04-16 00:21
> The group functionality seems like a nice feature @nikohd12 ... I never thought about it because I only have one team 😂
> 
> The most challenging point to implement would be:
> 
> > A possibility to introduce staggering mines by having a check before deploying other groups (is this possible?)
> 
> Maybe we can go ahead with grouping and leave this for later.

Yup. Totally agree with going with group functionality, just presented some pros with grouping. 

Thank you!

**Comment by theBlackEndDev** [comment] 2022-04-16 02:20
> The group functionality seems like a nice feature @nikohd12 ... I never thought about it because I only have one team joy
> 
> The most challenging point to implement would be:
> 
> > A possibility to introduce staggering mines by having a check before deploying other groups (is this possible?)
> 
> Maybe we can go ahead with grouping and leave this for later.

Groups would definitely be nice.  I currently just have all my teams in there twice grouped by mining and looting and just comment out the group that I'm not using.

**Comment by coccoinomane** [comment] 2022-04-21 12:08
Hi guys and @nikohd12 !

I have pushed a new branch [2022-04-21_teams-grouping](https://github.com/coccoinomane/crabada.py/tree/2022-04-21_teams-grouping) with the teams-grouping feature.

I have made a few tests, but with only one team my tests are obviously lacking.

Could you please test it and let me know if it is safe to merge with `master`?

Thanks,
Cocco

**Comment by nikohd12** [comment] 2022-04-21 12:11
> Hi guys and @nikohd12 !
> 
> I have pushed a new branch [2022-04-21_teams-grouping](https://github.com/coccoinomane/crabada.py/tree/2022-04-21_teams-grouping) with the teams-grouping feature.
> 
> I have made a few tests, but with only one team my tests are obviously lacking.
> 
> Could you please test it and let me know if it is safe to merge with `master`?
> 
> Thanks, Cocco
> 
> PS: You can use `python3 -m src.tests.testConfig` to see the team configuration, without the need to actually run the bot.

I will test this for the next 12 hours. Thank you as always @coccoinomane

**Comment by theBlackEndDev** [comment] 2022-04-21 12:20
Same I'll test this as well.

**Comment by nikohd12** [comment] 2022-04-21 12:26
Hi @coccoinomane,

I am getting the following errors

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/crabada-pool/src/tests/testConfig.py", line 1, in <module>
    from src.common.config import users, donatePercentage, nodeUri, notifications, telegram
  File "/home/ec2-user/crabada-pool/src/common/config.py", line 39, in <module>
    users.append(parseUserConfig(userNumber, teams))
  File "/home/ec2-user/crabada-pool/src/helpers/config.py", line 147, in parseUserConfig
    validateUserConfig(userConfig, userNumber)
  File "/home/ec2-user/crabada-pool/src/helpers/config.py", line 180, in validateUserConfig
    raise MissingConfig(f"User {userNumber} has no team configured")
src.common.exceptions.MissingConfig: User 1 has no team configured
```

My config looks like this:

```
# =========
# = MINER CRABOID =
# =========
USER_1_GROUP_1="300xx, 224xx, 22xx7, 20xx9, 196xx, 175xx4, 106xx, 95xx, 9xx4"
USER_1_GROUP_1_TASK="mine"
USER_1_GROUP_1_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMp"
USER_1_GROUP_1_REINFORCEMENT_TO_PICK="4"

# =========
# = MINER RUINED =
# =========
USER_1_GROUP_2="190xx, 190xx, 174xx, 108xx, 95xxx, 82xx"
USER_1_GROUP_2_TASK="mine"
USER_1_GROUP_2_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_GROUP_2_REINFORCEMENT_TO_PICK="4"

# =========
# = MINER SUNKEN =
# =========
USER_1_GROUP_3="21xxx"
USER_1_GROUP_3_TASK="mine"
USER_1_GROUP_3_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMpHighCost, HighestMp"
USER_1_GROUP_3_REINFORCEMENT_TO_PICK="4"

```

**Comment by nikohd12** [comment] 2022-04-21 12:29
EDIT:

I was able to fix by removing the commas and changing 

`USER_1_GROUP_1="300xx, 224xx, 22xx7, 20xx9, 196xx, 175xx4, 106xx, 95xx, 9xx4"`

to

`USER_1_GROUP_1_TEAMS="300xx,224xx,22xx7,20xx9,196xx,175xx4,106xx,95xx,9xx4"`

**Comment by coccoinomane** [comment] 2022-04-21 12:34
Ah, good find @nikohd12 !

I've fixed the readme: one should use `USER_1_GROUP_1_TEAMS` with the final `_TEAMS`.

The spaces after the commas are ignored, so you can leave them if you want 🙂

cc: @theBlackEndDev

**Comment by nikohd12** [comment] 2022-04-21 12:35
Alright! I'm going to test this out overnight.

Thanks @coccoinomane! So far so good here

**Comment by nikohd12** [comment] 2022-04-21 12:37
Reinforce_delay should work properly, right? @coccoinomane 

Btw, I have also tried USER_1_GROUP_1_REINFORCEMENT_TO_PICK="4" and it worked :)

**Comment by coccoinomane** [comment] 2022-04-21 12:38
Thanks @nikohd12 !

Yes, `REINFORCE_DELAY_IN_SECONDS` should work as intended.

I forgot to mention: if you need to add exceptions, you should be able to mix grouped teams with non-grouped teams:

```
USER_1_GROUP_1="300xx, 224xx, 22xx7, 20xx9, 196xx, 175xx4, 106xx, 95xx, 9xx4"
USER_1_GROUP_1_TASK="mine"
USER_1_GROUP_1_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMp"
USER_1_GROUP_1_REINFORCEMENT_TO_PICK="4"

USER_1_TEAM_1="9000"
USER_1_TEAM_1_TASK="mine
USER_1_GROUP_1_REINFORCE_STRATEGY="HighestMp, HighestMp"
USER_1_GROUP_1_REINFORCEMENT_TO_PICK="1"
```

**Comment by nikohd12** [comment] 2022-04-21 12:39
> Thanks @nikohd12 !
> 
> Yes, `REINFORCE_DELAY_IN_SECONDS` should work as intended.
> 
> I forgot to mention: if you need to add exceptions, you should be able to mix grouped teams with non-grouped teams:
> 
> ```
> USER_1_GROUP_1="300xx, 224xx, 22xx7, 20xx9, 196xx, 175xx4, 106xx, 95xx, 9xx4"
> USER_1_GROUP_1_TASK="mine"
> USER_1_GROUP_1_REINFORCE_STRATEGY="HighestMpFromInventory, HighestMp"
> USER_1_GROUP_1_REINFORCEMENT_TO_PICK="4"
> 
> USER_1_TEAM_1="9000"
> USER_1_TEAM_1_TASK="mine
> USER_1_GROUP_1_REINFORCE_STRATEGY="HighestMp, HighestMp"
> USER_1_GROUP_1_REINFORCEMENT_TO_PICK="1"
> ```
> 
> The non-grouped teams will be added to a fictious group with number zero (`0`).

Cool and neat feature! Thanks as always, @coccoinomane !

**Comment by theBlackEndDev** [comment] 2022-04-21 13:17
I was gonna report an issue but looks like you just pushed an update to the README which clears up the issue.  Thanks!

**Comment by theBlackEndDev** [comment] 2022-04-21 13:45
Ok this feature is really nice.  It gives granular control over your team's strategies.  Updated my cronjob to only use the one folder and will see how it works with automating my mine and loots together.

**Comment by nikohd12** [comment] 2022-04-23 04:29
Hi @coccoinomane,

No issues encountered for the past 24+ hrs. You may close this issue.

**Comment by coccoinomane** [comment] 2022-04-23 08:30
Thanks @nikohd12  and @theBlackEndDev for the testing 🙂

I have merged & closed the issue.

**Closed by coccoinomane** 2022-04-23 08:30 UTC
